# See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - manager/github-actions
          - cli-managed-by-jaxxstorm
    - title: Chores
      labels:
        - dependencies
        - manager/github-actions
        - cli-managed-by-jaxxstorm
